### ISSUE TITLE
merge all typescript declarations to single one

### ISSUE THREAD

**Issue by morlay** [preconstruct/preconstruct#247] opened 2020-01-20 02:15 UTC
related project: https://www.npmjs.com/package/rollup-plugin-dts

example:
https://github.com/querycap/reactorx

but have to use do extra build after preconstruct.

BTW, with typescript, `types` field not added by preconstruct.

**Comment by mitchellhamilton** [comment] 2020-01-30 23:30
This is something I'm interested in doing though I've looked at the various solutions that exist and they all seem to have edge cases where they break/they state that they're still unstable so I'd rather choose the stable solution that we have right now of not bundling them than one that could break and doesn't really have any tangible benefits.

> BTW, with typescript, types field not added by preconstruct.

Yep, that's fine because we create a dts file in a place that TS is able to resolve it.

**Comment by morlay** [comment] 2020-02-03 06:31
@mitchellhamilton 

multi dts files may make `auto imports` of IDEs or Editors import from sub file which is not really exists. 

Without "types" field, i think not each version of TS is able to resolve.

**Comment by mitchellhamilton** [comment] 2020-07-12 06:26
I haven't seen any problems with Preconstruct and VS Code's auto import. If you can reproduce the problem, feel free to open another issue.

Gonna close this issue since there's no tool that bundles TypeScript declarations very reliably.

**Closed by mitchellhamilton** 2020-07-12 06:26 UTC
