### ISSUE TITLE
Not compatible with vite

### ISSUE THREAD

**Issue by ocavue** [preconstruct/preconstruct#387] opened 2021-03-30 16:58 UTC
I tried to add [vite](https://github.com/vitejs/vite) into a TypeScript preconstruct monorepo. When I run `vite` to start a dev server, it throws the following errors:

```
& pnpm run dev 

> remirror-vite-example@1.0.0 dev /Users/ocavue/code/github/remirror_beta/examples/with-vite
> vite

 > ../../packages/remirror__extension-react-component/dist/remirror-extension-react-component.browser.esm.js:1:7: error: Unexpected "type"
    1 │ export type {
      ╵        ~~~~

 > ../../packages/remirror__extension-react-ssr/dist/remirror-extension-react-ssr.browser.esm.js:1:7: error: Unexpected "type"
    1 │ export type {
      ╵        ~~~~

 > ../../packages/remirror__react-core/dist/remirror-react-core.browser.esm.js:1:7: error: Unexpected "type"
    1 │ export type {
      ╵        ~~~~
```

It seems that vite doesn't accept the TypeScript code in the `packages/*/dist/*.browser.esm.js`. 

I can provide more information if you need.

**Comment by dbismut** [comment] 2021-04-20 09:58
@ocavue I think this is a duplicate of #378.

@Andarist I've reported the issue on the Vite repo but it seems to have stalled. Is having the esm file importing the entry point rather than aliasing to it off the table? That would solve it. I understand this is fixing someone else's problem though.

**Comment by Andarist** [comment] 2021-04-20 10:08
Yeah, it looks like the issue created by @dbismut: https://github.com/vitejs/vite/issues/2405 

I don't think there is anything actionable here, so I'm going to close this - hope you understand.

**Closed by Andarist** 2021-04-20 10:08 UTC

**Comment by ocavue** [comment] 2021-04-20 10:37
Thanks for your works. I will retry this once vitejs/vite#2405 has some progress.

**Comment by Andarist** [comment] 2021-04-20 11:58
@ocavue you could also try patching this temporarily on your own like here: https://github.com/pmndrs/leva/pull/129 . There is no guarantee that it will actually work for your case though - but there is a high chance that it might 😉
